---
- name: Fermer un ticket iTop via l'API REST
  hosts: localhost
  gather_facts: no
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php?version=1.3"
    itop_user: "rest_user"
    itop_pass: "RestUser@123"
    ticket_id: 1  # Valeur par défaut, remplacée par Semaphore

  tasks:
    - name: Fermer le ticket
      uri:
        url: "{{ itop_url }}"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body_format: form-urlencoded
        body:
          auth_user: "{{ itop_user }}"
          auth_pwd: "{{ itop_pass }}"
          json_data: >
            {{
              {
                "operation": "core/update",
                "class": "UserRequest",
                "key": ticket_id,
                "fields": {
                  "status": "closed",
                  "solution": "Fermé automatiquement par Ansible"
                }
              } | to_json
            }}
        return_content: yes
      register: result

    - name: Afficher la réponse de l'API
      debug:
        var: result.json
