---
- name: Configurer iTop (Base de données + Apache)
  hosts: itop
  become: yes
  vars:
    db_name: itop
    db_user: itopuser
    db_password: itoppass
    db_root_user: root
    db_root_password: rootpassword   
  tasks:
    - name: Installer pip3 si absent
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Installer le module PyMySQL pour Python 3
      pip:
        name: pymysql
        executable: pip3

    - name: Installer le paquet python3-mysqldb (optionnel, parfois utile)
      apt:
        name: python3-mysqldb
        state: present

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ db_root_user }}"
        login_password: "{{ db_root_password }}"

    - name: Créer l'utilisateur MySQL pour iTop
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: "{{ db_root_user }}"
        login_password: "{{ db_root_password }}"

    - name: Redémarrer MySQL pour prendre en compte les changements (si nécessaire)
      service:
        name: mysql
        state: restarted
      when: false  # mettre à true si besoin

    # Exemple simple de configuration Apache (à adapter)
    - name: Activer site iTop Apache
      file:
        src: /etc/apache2/sites-available/itop.conf
        dest: /etc/apache2/sites-enabled/itop.conf
        state: link
      notify:
        - Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
