---
- name: Redémarrer Prometheus avec la configuration SNMP déjà en place
  hosts: grafana
  become: yes
  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"

  tasks:
    - name: Sauvegarder l'ancien fichier prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Vérifier la validité du fichier prometheus.yml
      command: yamllint {{ prometheus_config_path }}
      register: yamllint_result
      failed_when: yamllint_result.rc != 0
      changed_when: false

    - name: Redémarrer Prometheus pour appliquer la configuration
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
