---
- name: Configure Prometheus server
  hosts: grafana
  become: yes

  tasks:
    - name: Deploy Prometheus configuration
      copy:
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                - targets:
                    - "10.0.57.34:9100"
                    - "10.0.57.35:9100"
                    - "10.0.57.36:9100"

            - job_name: 'redis_exporter'
              static_configs:
                - targets:
                    - "10.0.57.34:9121"
                    - "10.0.57.35:9121"
                    - "10.0.57.36:9121"

            - job_name: 'mysqld_exporter'
              static_configs:
                - targets:
                    - "10.0.57.34:9104"
                    - "10.0.57.35:9104"
                    - "10.0.57.36:9104"

            - job_name: 'nginx_exporter'
              static_configs:
                - targets:
                    - "10.0.57.34:9113"
                    - "10.0.57.35:9113"
                    - "10.0.57.36:9113"

      notify: Reload Prometheus

  handlers:
    - name: Reload Prometheus
      systemd:
        name: prometheus
        state: reloaded
