---
- name: Configurer Prometheus pour scrapper SNMP Exporter
  hosts: grafana
  become: yes
  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"

  tasks:
    - name: Sauvegarder l'ancien fichier prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Supprimer les anciennes configurations snmp déjà présentes
      replace:
        path: "{{ prometheus_config_path }}"
        regexp: '^\s*-\s*job_name:\s*[''"]?snmp[''"]?.*?static_configs:.*?(\n\s*-\s*targets:.*?(\n\s*-\s*.*?)*\n)+'
        replace: ''
      ignore_errors: yes

    - name: Ajouter la configuration SNMP Exporter au fichier prometheus.yml
      blockinfile:
        path: "{{ prometheus_config_path }}"
        marker: "# {mark} ANSIBLE SNMP EXPORTER CONFIG"
        block: |
          - job_name: 'snmp_ansible'
            metrics_path: /snmp
            params:
              module: [if_mib]
            static_configs:
              - targets:
                  - "10.0.57.34:9116"
                  - "10.0.57.35:9116"
                  - "10.0.57.36:9116"

    - name: Redémarrer Prometheus pour appliquer la nouvelle configuration
      systemd:
        name: prometheus
        state: restarted
        enabled: true
