---
- name: Configure Prometheus server scrape targets
  hosts: grafana
  become: yes
  gather_facts: yes

  vars:
    # Construire des listes cibles en dur (chaînes formatées)
    node_exporter_targets: |
      - 10.0.57.34:9100
      - 10.0.57.35:9100
      - 10.0.57.36:9100

    redis_exporter_targets: |
      - 10.0.57.34:9121
      - 10.0.57.35:9121
      - 10.0.57.36:9121

    mysqld_exporter_targets: |
      - 10.0.57.34:9104
      - 10.0.57.35:9104
      - 10.0.57.36:9104

    nginx_exporter_targets: |
      - 10.0.57.34:9113
      - 10.0.57.35:9113
      - 10.0.57.36:9113

  tasks:
    - name: Deploy Prometheus configuration with hardcoded scrape targets
      copy:
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                targets:
{{ node_exporter_targets | indent(18) }}

            - job_name: 'redis_exporter'
              static_configs:
                targets:
{{ redis_exporter_targets | indent(18) }}

            - job_name: 'mysqld_exporter'
              static_configs:
                targets:
{{ mysqld_exporter_targets | indent(18) }}

            - job_name: 'nginx_exporter'
              static_configs:
                targets:
{{ nginx_exporter_targets | indent(18) }}

      notify: Reload Prometheus

  handlers:
    - name: Reload Prometheus
      systemd:
        name: prometheus
        state: reloaded
