---
- name: Configurer Prometheus pour scrapper SNMP Exporter
  hosts: grafana
  become: yes
  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"

  tasks:
    - name: Sauvegarder l'ancien fichier prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Ajouter la configuration SNMP Exporter dans scrape_configs
      blockinfile:
        path: "{{ prometheus_config_path }}"
        marker: "# {mark} ANSIBLE SNMP EXPORTER CONFIG"
        insertafter: '^scrape_configs:'
        block: |
            - job_name: 'snmp_ansible'
              metrics_path: /snmp
              params:
                module: [if_mib]
              static_configs:
                - targets:
                    - "10.0.57.34:9116"
                    - "10.0.57.35:9116"
                    - "10.0.57.36:9116"

    - name: Redémarrer Prometheus pour appliquer la nouvelle configuration
      systemd:
        name: prometheus
        state: restarted
