---
- name: Configurer iTop (Base de données + Apache)
  hosts: all
  become: yes
  vars:
    mysql_root_user: root
    mysql_root_password: "root"
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass

  tasks:
    - name: Modifier bind-address pour autoriser toutes les connexions
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: Redémarrer MySQL pour appliquer la modification bind-address
      service:
        name: mysql
        state: restarted

    - name: S'assurer que python3-full est installé
      apt:
        name: python3-full
        state: present
        update_cache: yes

    - name: Installer PyMySQL en autorisant --break-system-packages
      command: >
        python3 -m pip install pymysql --break-system-packages
      args:
        creates: /usr/local/lib/python3*/dist-packages/pymysql

    - name: Autoriser l'utilisateur root à se connecter depuis n'importe où
      community.mysql.mysql_user:
        name: root
        host: "%"
        password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur MySQL pour iTop et accorder les droits
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
