---
- name: Configurer Prometheus pour surveiller les exporteurs SNMP
  hosts: prometheus
  become: yes
  vars:
    prometheus_config_path: /etc/prometheus/prometheus.yml

  tasks:
    - name: Sauvegarder l’ancien prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        mode: '0644'

    - name: Écrire le nouveau fichier de configuration Prometheus
      copy:
        dest: "{{ prometheus_config_path }}"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'snmp'
              static_configs:
                - targets: ['10.0.57.34:9116', '10.0.57.35:9116', '10.0.57.36:9116']
              metrics_path: /snmp
              params:
                module: [if_mib]

              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116
        mode: '0644'

    - name: Redémarrer Prometheus pour appliquer les modifications
      systemd:
        name: prometheus
        state: restarted
