---
- name: Configurer iTop
  hosts: itop
  become: yes

  tasks:
    - name: Créer le fichier de configuration
      copy:
        dest: "{{ itop_install_dir }}/conf/production/config-itop.php"
        content: |
          <?php
          return array(
              'db_host' => 'localhost',
              'db_port' => '3306',
              'db_user' => '{{ db_user }}',
              'db_pwd' => '{{ db_password }}',
              'db_name' => '{{ db_name }}',
              'db_driver' => 'mysql',
              'language' => 'fr_FR',
              'production_mode' => true,
          );
        owner: www-data
        group: www-data
        mode: '0640'

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
