---
- name: Configurer iTop (Base de données + Apache)
  hosts: itop-server
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    mysql_root_user: root
    mysql_root_password: "azerty"  # <-- À modifier
    db_name: itop
    db_user: itopuser
    db_password: itoppass

  tasks:
    - name: Installer pip3 si absent
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Installer le module PyMySQL pour Python 3
      pip:
        name: PyMySQL
        executable: pip3

    - name: Créer la base de données iTop
      mysql_db:
        name: "{{ db_name }}"
        state: present
      vars:
        ansible_mysql_user: "{{ mysql_root_user }}"
        ansible_mysql_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur MySQL pour iTop sur localhost
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
      vars:
        ansible_mysql_user: "{{ mysql_root_user }}"
        ansible_mysql_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur MySQL pour iTop depuis n'importe quelle IP
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: "%"
        state: present
      vars:
        ansible_mysql_user: "{{ mysql_root_user }}"
        ansible_mysql_password: "{{ mysql_root_password }}"

    - name: Rappel - vérifier bind-address dans MySQL
      debug:
        msg: |
          Vérifie que dans /etc/mysql/mysql.conf.d/mysqld.cnf la ligne suivante est présente et non commentée:
          bind-address = 0.0.0.0
          Puis redémarre MySQL:
          sudo systemctl restart mysql
