- name: Installer iTop en mode silencieux
  hosts: itop
  become: yes

  vars:
    mysql_root_user: root
    mysql_root_password: "root"
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass

  tasks:
    - name: Modifier bind-address pour autoriser toutes les connexions
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'

    - name: Redémarrer MySQL
      service:
        name: mysql
        state: restarted

    - name: Installer python3-full
      apt:
        name: python3-full
        state: present
        update_cache: yes

    - name: Installer PyMySQL
      command: python3 -m pip install pymysql --break-system-packages
      args:
        creates: /usr/local/lib/python3*/dist-packages/pymysql

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer l’utilisateur iTop
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Télécharger iTop pour récupérer itop_design
      get_url:
        url: https://sourceforge.net/projects/itop/files/latest/download
        dest: /tmp/itop.zip

    - name: Extraire l’archive iTop
      unarchive:
        src: /tmp/itop.zip
        dest: /tmp/
        remote_src: yes

    - name: Vérifier si le dossier iTop extrait existe
      stat:
        path: /tmp/iTop-*
      register: itop_extracted

    - name: Échec si aucun dossier iTop extrait trouvé
      fail:
        msg: "❌ Aucun dossier /tmp/iTop-* trouvé après extraction."
      when: not itop_extracted.stat.exists

    - name: Restaurer le dossier itop_design depuis l’archive extraite
      shell: |
        cp -r /tmp/iTop-*/itop_design /var/www/html/
      args:
        executable: /bin/bash

    - name: Appliquer les permissions sur itop_design
      file:
        path: /var/www/html/itop_design
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Vérifier la présence du fichier user_rights.xml
      stat:
        path: /var/www/html/itop_design/user_rights.xml
      register: user_rights_check

    - name: Échec si le fichier user_rights.xml est absent
      fail:
        msg: "❌ Le fichier /itop_design/user_rights.xml est manquant. Impossible de compiler le modèle."
      when: not user_rights_check.stat.exists

    - name: Créer le fichier XML de configuration silencieuse
      copy:
        dest: /var/www/html/web/setup/unattended-install/itop-config-silent.xml
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <itop_install>
            <target_env>production</target_env>
            <database>
              <server>localhost</server>
              <user>{{ itop_db_user }}</user>
              <pwd>{{ itop_db_password }}</pwd>
              <name>{{ itop_db_name }}</name>
              <prefix>itop_</prefix>
              <db_tls_enabled>false</db_tls_enabled>
              <db_tls_ca></db_tls_ca>
            </database>
            <admin_account>
              <user>admin</user>
              <pwd>admin123</pwd>
              <language>fr</language>
            </admin_account>
            <selected_modules>authent-local,itop-config-mgmt,itop-tickets,itop-incident-mgmt,itop-request-mgmt,itop-change-mgmt</selected_modules>
          </itop_install>

    - name: Remplacer sort() par un bloc sécurisé
      replace:
        path: /var/www/html/web/setup/unattended-install/unattended-install.php
        regexp: '^\s*sort\(\$aSelectedModules\);'
        replace: |
          if (!is_array($aSelectedModules)) {
              $aSelectedModules = explode(',', $aSelectedModules);
          }
          sort($aSelectedModules);

    - name: Créer le dossier requis pour la compilation
      file:
        path: /var/www/html/web/datamodels/latest
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Appliquer les permissions sur /var/www/html
      file:
        path: /var/www/html
        recurse: yes
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Lancer l’installation silencieuse de iTop
      command: php unattended-install.php --param-file=itop-config-silent.xml
      args:
        chdir: /var/www/html/web/setup/unattended-install
