- name: Installer iTop en mode silencieux
  hosts: itop
  become: yes

  vars:
    mysql_root_user: root
    mysql_root_password: "root"
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass

  tasks:
    - name: Modifier bind-address pour autoriser toutes les connexions
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'

    - name: Redémarrer MySQL
      service:
        name: mysql
        state: restarted

    - name: Installer python3-full
      apt:
        name: python3-full
        state: present
        update_cache: yes

    - name: Installer PyMySQL
      command: python3 -m pip install pymysql --break-system-packages
      args:
        creates: /usr/local/lib/python3*/dist-packages/pymysql

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer l’utilisateur iTop
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer le fichier XML de configuration silencieuse
      copy:
        dest: /var/www/html/web/setup/unattended-install/itop-config-silent.xml
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <itop_install>
            <target_env>production</target_env>
            <database>
              <server>localhost</server>
              <user>{{ itop_db_user }}</user>
              <pwd>{{ itop_db_password }}</pwd>
              <name>{{ itop_db_name }}</name>
              <prefix>itop_</prefix>
            </database>
            <selected_modules>authent-local,itop-config-mgmt,itop-tickets,itop-incident-mgmt,itop-request-mgmt,itop-change-mgmt</selected_modules>
          </itop_install>

    - name: Remplacer le sort() par un bloc sécurisé dans unattended-install.php
      replace:
        path: /var/www/html/web/setup/unattended-install/unattended-install.php
        regexp: '^\s*sort\(\$aSelectedModules\);'
        replace: |
          if (!is_array($aSelectedModules)) {
              $aSelectedModules = explode(',', $aSelectedModules);
          }
          sort($aSelectedModules);

    - name: S'assurer que /var/www/html a les bonnes permissions
      file:
        path: /var/www/html
        recurse: yes
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Créer le dossier requis par iTop (si non existant)
      file:
        path: /var/www/html/web/datamodels/latest
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Lancer l’installation silencieuse de iTop
      command: php unattended-install.php --param-file=itop-config-silent.xml
      args:
        chdir: /var/www/html/web/setup/unattended-install
