---
- name: Configurer Prometheus pour scrapper SNMP Exporter
  hosts: prometheus
  become: yes
  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"
    snmp_targets:
      - "10.0.57.34:9116"
      - "10.0.57.35:9116"
      - "10.0.57.36:9116"

  tasks:
    - name: Installer Prometheus (si pas encore installé)
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Sauvegarder l'ancien prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Ajouter le job SNMP Exporter
      blockinfile:
        path: "{{ prometheus_config_path }}"
        marker: "# {mark} ANSIBLE SNMP EXPORTER CONFIG"
        block: |
          - job_name: 'snmp'
            static_configs:
              - targets:
{% for target in snmp_targets %}
                  - '{{ target }}'
{% endfor %}
            metrics_path: /snmp
            params:
              module: [if_mib]

    - name: Vérifier la validité du fichier prometheus.yml
      command: promtool check config {{ prometheus_config_path }}
      register: promtool_result
      failed_when: "'SUCCESS' not in promtool_result.stdout"
      changed_when: false
      ignore_errors: yes

    - name: Redémarrer Prometheus
      systemd:
        name: prometheus
        state: restarted
      when: promtool_result is succeeded
