---
- name: Configurer iTop (Base de données + Apache)
  hosts: itop
  become: yes
  vars:
    db_name: "itop_db"
    db_user: "itop_user"
    db_password: "itop_password"
    mysql_root_password: "rootpass"
    itop_install_dir: "/var/www/html/itop"

  tasks:
    - name: Créer la base de données iTop
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Créer l'utilisateur MySQL pour iTop
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: "localhost"
        state: present

    - name: S'assurer que Apache écoute sur le port 80
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 80'
        state: present

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
