---
- name: Configurer iTop (Base de données + installation silencieuse)
  hosts: itop
  become: yes

  vars:
    mysql_root_user: root
    mysql_root_password: "root"
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass
    itop_web_dir: "/var/www/html"

  tasks:
    - name: Modifier bind-address pour accepter les connexions distantes
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'
        backup: yes

    - name: Redémarrer MySQL
      service:
        name: mysql
        state: restarted

    - name: Installer PyMySQL
      command: python3 -m pip install pymysql --break-system-packages
      args:
        creates: /usr/local/lib/python3*/dist-packages/pymysql

    - name: Autoriser root à se connecter depuis n'importe où
      community.mysql.mysql_user:
        name: root
        host: "%"
        password: "{{ mysql_root_password }}"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer l'utilisateur iTop et accorder les droits
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Créer le fichier de configuration silent XML
      copy:
        dest: "{{ itop_web_dir }}/web/itop-config-silent.xml"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <parameters>
            <database_host>localhost</database_host>
            <database_name>{{ itop_db_name }}</database_name>
            <database_user>{{ itop_db_user }}</database_user>
            <database_pwd>{{ itop_db_password }}</database_pwd>
            <admin_account>admin</admin_account>
            <admin_pwd>admin</admin_pwd>
            <admin_pwd_confirm>admin</admin_pwd_confirm>
            <language>fr</language>
            <sample_data>yes</sample_data>
          </parameters>

    - name: Lancer l'installation silencieuse de iTop
      command: php setup.php --production --db-setup --config-file=itop-config-silent.xml
      args:
        chdir: "{{ itop_web_dir }}/web"

    - name: Redémarrer Apache après installation
      service:
        name: apache2
        state: restarted
