---
- name: Configurer Prometheus pour surveiller les exporteurs SNMP
  hosts: prometheus
  become: yes
  vars:
    prometheus_config_path: /etc/prometheus/prometheus.yml

  tasks:
    - name: Sauvegarder l’ancien prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        mode: '0644'

    - name: Écrire le nouveau fichier de configuration Prometheus avec plusieurs modules SNMP
      copy:
        dest: "{{ prometheus_config_path }}"
        content: |
          global:
            scrape_interval: 15s

          scrape_configs:
            - job_name: 'snmp_if_mib'
              static_configs:
                - targets: ['10.0.57.34:161', '10.0.57.35:161', '10.0.57.36:161']
              metrics_path: /snmp
              params:
                module: [if_mib]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116

            - job_name: 'snmp_system'
              static_configs:
                - targets: ['10.0.57.34:161', '10.0.57.35:161', '10.0.57.36:161']
              metrics_path: /snmp
              params:
                module: [system]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116

            - job_name: 'snmp_ucd'
              static_configs:
                - targets: ['10.0.57.34:161', '10.0.57.35:161', '10.0.57.36:161']
              metrics_path: /snmp
              params:
                module: [ucd]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116

            - job_name: 'snmp_host'
              static_configs:
                - targets: ['10.0.57.34:161', '10.0.57.35:161', '10.0.57.36:161']
              metrics_path: /snmp
              params:
                module: [host]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116

            - job_name: 'snmp_netstat'
              static_configs:
                - targets: ['10.0.57.34:161', '10.0.57.35:161', '10.0.57.36:161']
              metrics_path: /snmp
              params:
                module: [netstat]
              relabel_configs:
                - source_labels: [__address__]
                  target_label: __param_target
                - source_labels: [__param_target]
                  target_label: instance
                - target_label: __address__
                  replacement: localhost:9116
        mode: '0644'

    - name: Recharger systemd
      systemd:
        daemon_reload: yes

    - name: Redémarrer Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes

    - name: Vérifier que Prometheus est prêt
      uri:
        url: http://localhost:9090/-/ready
        method: GET
        return_content: yes
      register: prometheus_status

    - name: Afficher le statut de Prometheus
      debug:
        msg: "Prometheus est prêt : {{ prometheus_status.status }} - {{ prometheus_status.content }}"
