---
- name: Configurer Prometheus pour scrapper SNMP Exporter
  hosts: prometheus
  become: yes
  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"
    snmp_exporter_target: "10.0.57.36:9116"  # port par défaut snmp_exporter

  tasks:
    - name: Installer Prometheus (si pas encore installé)
      apt:
        name: prometheus
        state: present
        update_cache: yes

    - name: Sauvegarder l'ancien fichier prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.backup"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Ajouter la configuration SNMP Exporter au fichier prometheus.yml
      blockinfile:
        path: "{{ prometheus_config_path }}"
        marker: "# {mark} ANSIBLE SNMP EXPORTER CONFIG"
        block: |
          - job_name: 'snmp_exporter'
            static_configs:
              - targets: ['{{ snmp_exporter_target }}']
            metrics_path: /snmp
            params:
              module: [default]
    - name: Redémarrer Prometheus pour prendre en compte la nouvelle config
      systemd:
        name: prometheus
        state: restarted
