---
- name: Configurer Prometheus pour intégrer SNMP Exporter
  hosts: grafana
  become: yes

  vars:
    prometheus_config_path: "/etc/prometheus/prometheus.yml"

  tasks:
    - name: Sauvegarder l'ancien fichier prometheus.yml
      copy:
        src: "{{ prometheus_config_path }}"
        dest: "{{ prometheus_config_path }}.bak"
        remote_src: yes
        backup: yes
      ignore_errors: yes

    - name: Déployer le fichier prometheus.yml avec job SNMP
      copy:
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'snmp'
              static_configs:
                - targets:
                    - 10.0.57.35:9116
                    - 10.0.57.36:9116
                    - 10.0.57.34:9116
              metrics_path: /snmp
              params:
                module: [if_mib]
        dest: "{{ prometheus_config_path }}"
        mode: '0644'
      notify: Restart prometheus

  handlers:
    - name: Restart prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
