---
- name: Installer iTop en mode silencieux (version 3.x+)
  hosts: itop
  become: yes

  vars:
    mysql_root_user: root
    mysql_root_password: "root"
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass
    itop_install_dir: "/var/www/html/web"

  tasks:
    - name: Modifier bind-address MySQL pour autoriser toutes les connexions
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address\s*='
        line: 'bind-address = 0.0.0.0'

    - name: Redémarrer MySQL
      service:
        name: mysql
        state: restarted

    - name: Installer python3-full
      apt:
        name: python3-full
        state: present
        update_cache: yes

    - name: Installer PyMySQL
      command: python3 -m pip install pymysql --break-system-packages
      args:
        creates: /usr/local/lib/python3*/dist-packages/pymysql

    - name: Créer la base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer l’utilisateur iTop MySQL avec privilèges
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    - name: Créer le fichier XML de configuration silencieuse
      copy:
        dest: "{{ itop_install_dir }}/setup/itop-config-silent.xml"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <itop_install>
            <target_env>production</target_env>
            <database>
              <server>localhost</server>
              <user>{{ itop_db_user }}</user>
              <pwd>{{ itop_db_password }}</pwd>
              <name>{{ itop_db_name }}</name>
              <prefix>itop_</prefix>
              <db_tls_enabled>false</db_tls_enabled>
              <db_tls_ca></db_tls_ca>
            </database>
            <admin_account>
              <user>admin</user>
              <pwd>admin123</pwd>
              <language>fr</language>
            </admin_account>
            <selected_modules>
              authent-local,itop-config-mgmt,itop-tickets,itop-incident-mgmt,itop-request-mgmt,itop-change-mgmt
            </selected_modules>
          </itop_install>

    - name: Remplacer sort() par un bloc sécurisé dans unattended-install.php
      replace:
        path: "{{ itop_install_dir }}/setup/unattended-install/unattended-install.php"
        regexp: '^\s*sort\(\$aSelectedModules\);'
        replace: |
          if (!is_array($aSelectedModules)) {
              $aSelectedModules = explode(',', $aSelectedModules);
          }
          sort($aSelectedModules);

    - name: Créer dossier requis pour compilation
      file:
        path: "{{ itop_install_dir }}/datamodels/latest"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Appliquer permissions sur {{ itop_install_dir }}
      file:
        path: "{{ itop_install_dir }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Lancer l’installation silencieuse iTop
      command: >
        php unattended-install.php --param-file=../itop-config-silent.xml
      args:
        chdir: "{{ itop_install_dir }}/setup/unattended-install"
