---
- name: Configurer et installer iTop en mode silencieux (3.x)
  hosts: itop
  become: yes

  vars:
    mysql_root_user: root
    mysql_root_password: root
    itop_db_name: itop
    itop_db_user: itopuser
    itop_db_password: itoppass
    itop_install_dir: /var/www/html/web
    itop_config_file: itop-config-silent.xml

  tasks:
    - name: Créer base de données iTop
      community.mysql.mysql_db:
        name: "{{ itop_db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
      notify: Restart MySQL

    - name: Créer utilisateur MySQL iTop avec droits
      community.mysql.mysql_user:
        name: "{{ itop_db_user }}"
        password: "{{ itop_db_password }}"
        priv: "{{ itop_db_name }}.*:ALL"
        host: "%"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"
      notify: Restart MySQL

    - name: Créer fichier XML config silencieuse iTop
      copy:
        dest: "{{ itop_install_dir }}/setup/{{ itop_config_file }}"
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <itop_install>
            <target_env>production</target_env>
            <database>
              <server>localhost</server>
              <user>{{ itop_db_user }}</user>
              <pwd>{{ itop_db_password }}</pwd>
              <name>{{ itop_db_name }}</name>
              <prefix>itop_</prefix>
              <db_tls_enabled>false</db_tls_enabled>
              <db_tls_ca></db_tls_ca>
            </database>
            <admin_account>
              <user>admin</user>
              <pwd>admin123</pwd>
              <language>fr</language>
            </admin_account>
            <selected_modules>
              authent-local,itop-config-mgmt,itop-tickets,itop-incident-mgmt,itop-request-mgmt,itop-change-mgmt
            </selected_modules>
          </itop_install>

    - name: Appliquer permissions dossier iTop web
      file:
        path: "{{ itop_install_dir }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Lancer installation silencieuse iTop
      command: >
        php unattended-install/unattended-install.php --param-file=setup/{{ itop_config_file }}
      args:
        chdir: "{{ itop_install_dir }}"
      register: install_output
      failed_when: install_output.rc != 0
      no_log: false

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
