---
- name: Configurer iTop (Base de données + Apache)
  hosts: all
  become: yes
  vars:
    db_name: itop
    db_user: itop
    db_password: itoppass

  tasks:
    - name: Installer pip3 si absent
      apt:
        name: python3-pip
        state: present

    - name: Installer le module PyMySQL pour Python 3
      apt:
        name: python3-pymysql
        state: present

    - name: Créer la base de données iTop
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Créer l'utilisateur MySQL pour iTop
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present

    - name: Copier fichier de configuration Apache iTop (directement dans le playbook)
      copy:
        dest: /etc/apache2/sites-available/itop.conf
        owner: root
        group: root
        mode: '0644'
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@localhost
              DocumentRoot /var/www/html

              <Directory /var/www/html>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/itop_error.log
              CustomLog ${APACHE_LOG_DIR}/itop_access.log combined
          </VirtualHost>

    - name: Activer site iTop Apache
      command: a2ensite itop.conf
      args:
        creates: /etc/apache2/sites-enabled/itop.conf

    - name: Activer le module rewrite Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Désactiver le site Apache par défaut
      command: a2dissite 000-default.conf
      args:
        removes: /etc/apache2/sites-enabled/000-default.conf
      ignore_errors: yes

    - name: Redémarrer Apache pour appliquer les changements
      service:
        name: apache2
        state: restarted
