---
- name: Création serveur iTop avec collecte auto des infos
  hosts: all
  gather_facts: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    default_org_id: "API Users"
    default_location_id: "Bamako"
    default_rack_id: "Rack1"
    move2production: "2024-06-01"
    purchase_date: "2024-05-01"
    end_of_warranty: "2027-05-01"

  tasks:
    - name: Définir les faits système pour recherche
      set_fact:
        brand_name: "{{ ansible_product_name.split()[0] | default('Generic') }}"
        model_name: "{{ ansible_product_name | default('Generic Model') }}"
        os_family: "{{ ansible_os_family | default('Linux') }}"
        os_version: "{{ ansible_distribution_version | default('1.0') }}"

    - name: Obtenir brand_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Brand",
                "key": "name = '" ~ brand_name ~ "'"
              } | to_json
            }}
      register: brand_result

    - name: Extraire brand_id
      set_fact:
        brand_id: "{{ (brand_result.json.objects | dict2items | first).value.key | default(None) }}"
      when: brand_result.json.objects is defined and brand_result.json.objects | length > 0

    - name: Obtenir model_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Model",
                "key": "name = '" ~ model_name ~ "'"
              } | to_json
            }}
      register: model_result

    - name: Extraire model_id
      set_fact:
        model_id: "{{ (model_result.json.objects | dict2items | first).value.key | default(None) }}"
      when: model_result.json.objects is defined and model_result.json.objects | length > 0

    - name: Obtenir osfamily_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "OSFamily",
                "key": "name = '" ~ os_family ~ "'"
              } | to_json
            }}
      register: osfamily_result

    - name: Extraire osfamily_id
      set_fact:
        osfamily_id: "{{ (osfamily_result.json.objects | dict2items | first).value.key | default(None) }}"
      when: osfamily_result.json.objects is defined and osfamily_result.json.objects | length > 0

    - name: Obtenir osversion_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "OSVersion",
                "key": "name = '" ~ os_version ~ "'"
              } | to_json
            }}
      register: osversion_result

    - name: Extraire osversion_id
      set_fact:
        osversion_id: "{{ (osversion_result.json.objects | dict2items | first).value.key | default(None) }}"
      when: osversion_result.json.objects is defined and osversion_result.json.objects | length > 0

    - name: Vérifier que tous les IDs sont présents
      fail:
        msg: "Échec : un ou plusieurs objets nécessaires (Brand, Model, OSFamily, OSVersion) sont introuvables dans iTop."
      when: brand_id is none or model_id is none or osfamily_id is none or osversion_id is none

    - name: Créer le serveur dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: true
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/create",
                "class": "Server",
                "comment": "Créé automatiquement depuis Ansible",
                "fields": {
                  "name": inventory_hostname,
                  "org_id": default_org_id,
                  "status": "production",
                  "business_criticity": "medium",
                  "location_id": default_location_id,
                  "rack_id": default_rack_id,
                  "brand_id": brand_id,
                  "model_id": model_id,
                  "osfamily_id": osfamily_id,
                  "osversion_id": osversion_id,
                  "cpu": ansible_processor[0] | default("Unknown CPU"),
                  "ram": ansible_memtotal_mb | default("0"),
                  "nb_u": "2",
                  "serialnumber": "SRV-" ~ ansible_default_ipv4.address,
                  "asset_number": "AST-" ~ ansible_default_ipv4.address,
                  "move2production": move2production,
                  "purchase_date": purchase_date,
                  "end_of_warranty": end_of_warranty,
                  "description": "Créé automatiquement depuis Ansible"
                }
              } | to_json
            }}
      register: creation_result
      failed_when: creation_result.json.code != 0

    - name: Afficher la réponse iTop
      debug:
        var: creation_result.json
