---
- name: Création serveur iTop avec collecte auto des infos
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    default_org_id: "4"  # API Users
    default_location_id: "3"  # Paris
    default_rack_id: "15"  # Rack1
    default_model_id: "44"  # DL380
    default_brand_id: "14"  # IBM
    default_osfamily_id: "24"  # Ubuntu
    default_osversion_id: "33"  # 20.04 LTS

  tasks:

    - name: Récupérer la marque du serveur
      command: dmidecode -s system-manufacturer
      register: manufacturer_output
      changed_when: false
      failed_when: manufacturer_output.rc != 0 and manufacturer_output.rc != 1

    - name: Récupérer le modèle du serveur
      command: dmidecode -s system-product-name
      register: model_output
      changed_when: false
      failed_when: model_output.rc != 0 and model_output.rc != 1

    - name: Envoi du serveur dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/create",
                "class": "Server",
                "comment": "Créé automatiquement depuis Ansible avec données enrichies",
                "fields": {
                  "name": inventory_hostname,
                  "org_id": default_org_id,
                  "status": "production",
                  "business_criticity": "low",
                  "location_id": default_location_id,
                  "rack_id": default_rack_id,
                  "brand_id": default_brand_id,
                  "model_id": default_model_id,
                  "osfamily_id": default_osfamily_id,
                  "osversion_id": default_osversion_id,
                  "cpu": "{{ ansible_processor[1] | default('Unknown') }}",
                  "ram": "{{ ansible_memtotal_mb | default('0') }}",
                  "nb_u": "2",
                  "serialnumber": "SRV-{{ ansible_default_ipv4.address }}",
                  "asset_number": "AST-{{ ansible_default_ipv4.address }}",
                  "move2production": "2024-06-01",
                  "purchase_date": "2024-05-01",
                  "end_of_warranty": "2027-05-01",
                  "description": "Créé automatiquement depuis Ansible avec données enrichies"
                }
              } | to_json
            }}
        status_code: 200
      register: itop_response

    - name: Afficher la réponse de l’API iTop
      debug:
        var: itop_response.json
