---
- name: Création serveur iTop avec collecte auto des infos
  hosts: all
  gather_facts: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    default_org_id: "API Users"
    default_location_id: "Bamako"
    default_rack_id: "Rack1"
    move2production: "2024-06-01"
    purchase_date: "2024-05-01"
    end_of_warranty: "2027-05-01"

  tasks:
    - name: Déduire les infos système
      set_fact:
        brand_name: "{{ ansible_product_name.split()[0] | default('HP') }}"
        model_name: "{{ ansible_product_name | default('HP ProLiant') }}"
        os_family: "{{ ansible_os_family | default('Linux') }}"
        os_version: "{{ ansible_distribution_version | default('24.04') }}"

    - name: Obtenir brand_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Brand",
                "key": "SELECT Brand WHERE name='{{ brand_name }}'",
                "version": "1.3"
              } | to_json
            }}
      register: brand_response

    - name: Obtenir model_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Model",
                "key": "SELECT Model WHERE name='{{ model_name }}'",
                "version": "1.3"
              } | to_json
            }}
      register: model_response

    - name: Obtenir osfamily_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "OSFamily",
                "key": "SELECT OSFamily WHERE name='{{ os_family }}'",
                "version": "1.3"
              } | to_json
            }}
      register: osfamily_response

    - name: Obtenir osversion_id depuis iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "OSVersion",
                "key": "SELECT OSVersion WHERE name='{{ os_version }}'",
                "version": "1.3"
              } | to_json
            }}
      register: osversion_response

    - name: Définir les IDs complets pour iTop
      set_fact:
        brand_id: "Brand::{{ (brand_response.json.objects | dict2items)[0].key }}"
        model_id: "Model::{{ (model_response.json.objects | dict2items)[0].key }}"
        osfamily_id: "OSFamily::{{ (osfamily_response.json.objects | dict2items)[0].key }}"
        osversion_id: "OSVersion::{{ (osversion_response.json.objects | dict2items)[0].key }}"

    - name: Vérifier que tous les IDs existent
      fail:
        msg: "Un des objets (marque, modèle, OS) est introuvable dans iTop."
      when:
        - brand_id is not defined
        - model_id is not defined
        - osfamily_id is not defined
        - osversion_id is not defined

    - name: Envoi du serveur dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >-
            {{
              {
                "version": "1.3",
                "operation": "core/create",
                "class": "Server",
                "comment": "Créé automatiquement depuis Ansible",
                "fields": {
                  "name": inventory_hostname,
                  "org_id": default_org_id,
                  "status": "production",
                  "business_criticity": "low",
                  "location_id": default_location_id,
                  "rack_id": default_rack_id,
                  "brand_id": brand_id,
                  "model_id": model_id,
                  "osfamily_id": osfamily_id,
                  "osversion_id": osversion_id,
                  "cpu": ansible_processor[1] | default('Unknown'),
                  "ram": ansible_memtotal_mb | default('0'),
                  "nb_u": "2",
                  "serialnumber": "SRV-" + ansible_default_ipv4.address,
                  "asset_number": "AST-" + ansible_default_ipv4.address,
                  "move2production": move2production,
                  "purchase_date": purchase_date,
                  "end_of_warranty": end_of_warranty,
                  "description": "Créé automatiquement depuis Ansible avec détection auto des infos"
                }
              } | to_json
            }}
      register: create_response

    - name: Afficher la réponse de création
      debug:
        var: create_response.json
