- name: Enregistrer les serveurs dans iTop
  hosts: all
  gather_facts: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    default_org_id: "4"           # API Users
    default_location_id: "3"      # Bamako

  tasks:

    - name: Générer les données serveur à envoyer
      set_fact:
        server_data:
          version: "1.3" 
          operation: "core/create"
          comment: "Création d’un serveur depuis Ansible"
          class: "Server"
          fields:
            name: "{{ ansible_hostname }}"
            org_id: "{{ default_org_id }}"
            location_id: "{{ default_location_id }}"
            cpu: "{{ ansible_processor[1] | default('N/A') }}"
            ram: "{{ ansible_memtotal_mb | default('0') }} MB"
            osfamily: "{{ ansible_os_family }}"
            osversion: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
            description: "Créé automatiquement par Ansible"

    - name: Envoi à iTop via l’API REST
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: json
        body: "{{ server_data }}"
        return_content: yes
      register: itop_response

    - name: Afficher la réponse de l'API
      debug:
        var: itop_response.json
