---
- name: Envoi complet des serveurs vers iTop via l’API REST
  hosts: itop_clients
  gather_facts: yes

  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    itop_version: "1.3"

    # Valeurs fixes extraites du test manuel réussi
    org_id: 4              # API Users
    location_id: 3         # Paris
    rack_id: 15            # Rack1
    brand_id: 14           # IBM
    model_id: 44           # DL380
    osfamily_id: 24        # Ubuntu
    osversion_id: 33       # 20.04 LTS

    purchase_date: "2024-05-01"
    move2production: "2024-06-01"
    end_of_warranty: "2027-05-01"

  tasks:
    - name: Construire les données serveur à envoyer
      set_fact:
        server_payload:
          version: "{{ itop_version }}"
          operation: "core/create"
          class: "Server"
          comment: "Ajout automatique enrichi depuis Ansible"
          fields:
            name: "{{ ansible_hostname }}"
            org_id: "{{ org_id }}"
            status: "production"
            business_criticity: "low"
            location_id: "{{ location_id }}"
            rack_id: "{{ rack_id }}"
            brand_id: "{{ brand_id }}"
            model_id: "{{ model_id }}"
            osfamily_id: "{{ osfamily_id }}"
            osversion_id: "{{ osversion_id }}"
            cpu: "{{ ansible_processor[1] | default('Intel Xeon') }}"
            ram: "{{ ansible_memtotal_mb | default('8192') }}"
            nb_u: "2"
            serialnumber: "SRV-{{ inventory_hostname }}"
            asset_number: "AST-{{ inventory_hostname }}"
            move2production: "{{ move2production }}"
            purchase_date: "{{ purchase_date }}"
            end_of_warranty: "{{ end_of_warranty }}"
            description: "Créé automatiquement depuis Ansible avec données enrichies"

    - name: Envoyer les données du serveur vers iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: "{{ server_payload | to_json }}"
        return_content: yes
      register: itop_response

    - name: Afficher la réponse d’iTop
      debug:
        var: itop_response.json
