---
- name: Création serveur iTop avec collecte auto des infos
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    default_org_id: "4"
    default_location_id: "3"
    default_rack_id: "15"

  tasks:

    - name: Récupérer la marque du serveur
      command: dmidecode -s system-manufacturer
      register: manufacturer_output
      changed_when: false
      failed_when: manufacturer_output.rc != 0 and manufacturer_output.rc != 1

    - name: Récupérer le modèle du serveur
      command: dmidecode -s system-product-name
      register: model_output
      changed_when: false
      failed_when: model_output.rc != 0 and model_output.rc != 1

    - name: Définir les variables dynamiques
      set_fact:
        server_brand: "{{ manufacturer_output.stdout | trim }}"
        server_model: "{{ model_output.stdout | trim }}"
        os_family: "{{ ansible_distribution | trim }}"
        os_version: "{{ ansible_distribution_version | trim }}"
        move2production: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        purchase_date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
        end_of_warranty: "{{ lookup('pipe', 'date -d \"3 years\" +%Y-%m-%d') }}"

    - name: Obtenir l'ID de la marque dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/get",
                "class": "Brand",
                "key": "name='{{ server_brand }}'"
              } | to_json
            }}
        status_code: 200
      register: brand_response

    - name: Obtenir l'ID du modèle dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/get",
                "class": "Model",
                "key": "name='{{ server_model }}'"
              } | to_json
            }}
        status_code: 200
      register: model_response

    - name: Obtenir l'ID de la famille OS dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/get",
                "class": "OSFamily",
                "key": "name='{{ os_family }}'"
              } | to_json
            }}
        status_code: 200
      register: osfamily_response

    - name: Obtenir l'ID de la version OS dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/get",
                "class": "OSVersion",
                "key": "name='{{ os_version }}'"
              } | to_json
            }}
        status_code: 200
      register: osversion_response

    - name: Vérifier que tous les IDs existent
      fail:
        msg: "L'un des objets (marque, modèle, OS) est introuvable dans iTop."
      when: >
        brand_response.json.objects is not defined or
        model_response.json.objects is not defined or
        osfamily_response.json.objects is not defined or
        osversion_response.json.objects is not defined

    - name: Envoi du serveur dans iTop
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "version": "1.3",
                "operation": "core/create",
                "class": "Server",
                "comment": "Créé automatiquement depuis Ansible avec détection auto des infos",
                "fields": {
                  "name": inventory_hostname,
                  "org_id": default_org_id,
                  "status": "production",
                  "business_criticity": "low",
                  "location_id": default_location_id,
                  "rack_id": default_rack_id,
                  "brand_id": (brand_response.json.objects.values() | list | first).key,
                  "model_id": (model_response.json.objects.values() | list | first).key,
                  "osfamily_id": (osfamily_response.json.objects.values() | list | first).key,
                  "osversion_id": (osversion_response.json.objects.values() | list | first).key,
                  "cpu": "{{ ansible_processor[1] | default('Unknown') }}",
                  "ram": "{{ ansible_memtotal_mb | default('0') }}",
                  "nb_u": "2",
                  "serialnumber": "SRV-{{ ansible_default_ipv4.address }}",
                  "asset_number": "AST-{{ ansible_default_ipv4.address }}",
                  "move2production": "{{ move2production }}",
                  "purchase_date": "{{ purchase_date }}",
                  "end_of_warranty": "{{ end_of_warranty }}",
                  "description": "Créé automatiquement depuis Ansible avec détection auto des infos"
                }
              } | to_json
            }}
        status_code: 200
      register: itop_response

    - name: Afficher la réponse iTop
      debug:
        var: itop_response.json
