---
- name: Envoyer les serveurs vers iTop via API REST
  hosts: itop_clients
  gather_facts: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"
    itop_version: "1.3"
    org_id: 4  # Doit exister dans iTop (ex : "API Users")

  tasks:
    - name: Construire les données serveur pour iTop
      set_fact:
        server_payload:
          version: "{{ itop_version }}"
          operation: "core/create"
          class: "Server"
          comment: "Ajout automatique depuis Ansible"
          fields:
            name: "{{ ansible_hostname }}"
            org_id: "{{ org_id }}"
            status: "production"
            criticality: "low"
            os_family: "{{ ansible_os_family }}"
            cpu: "{{ ansible_processor[1] | default('Unknown') }}"
            ram: "{{ ansible_memtotal_mb }}"
            description: "Serveur ajouté automatiquement via Ansible"
            management_ip: "{{ ansible_default_ipv4.address }}"
            # optionnels, à ajouter selon ton modèle iTop :
            # brand_id: "Dell"
            # model_id: "PowerEdge"
            # location_id: "1"
            # move2rack_id: "1"
            # move2chassis_id: "1"

    - name: Envoyer les données à iTop via API REST
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: "{{ server_payload | to_json }}"
        return_content: yes
      register: itop_response

    - name: Afficher la réponse d’iTop
      debug:
        var: itop_response.json
