---
- name: Générer et déployer snmp.yml avec tous les modules nécessaires
  hosts: grafana
  become: yes
  vars:
    generator_dir: /opt/snmp_exporter_generator
    snmp_yml_dest: /etc/snmp_exporter/snmp.yml

  tasks:
    - name: Installer les dépendances nécessaires
      apt:
        name:
          - git
          - make
          - golang-go
          - libsnmp-dev  # Dépendance manquante pour compiler les MIBs
        state: present
        update_cache: yes

    - name: Supprimer l'ancien générateur si présent
      file:
        path: "{{ generator_dir }}"
        state: absent

    - name: Cloner le dépôt snmp_exporter
      git:
        repo: https://github.com/prometheus/snmp_exporter.git
        dest: "{{ generator_dir }}"

    - name: Créer le fichier generator.yml avec les modules requis
      copy:
        dest: "{{ generator_dir }}/generator/generator.yml"
        content: |
          modules:
            host:
              walk: [iso.3.6.1.2.1.1]
              version: 2
            system:
              walk: [iso.3.6.1.2.1.1, iso.3.6.1.2.1.25.1]
              version: 2
            if_mib:
              walk: [interfaces, ifXTable]
              version: 2
            netstat:
              walk: [iso.3.6.1.2.1.6]
              version: 2
            ucd:
              walk:
                - .1.3.6.1.4.1.2021.4
                - .1.3.6.1.4.1.2021.10
                - .1.3.6.1.4.1.2021.11
                - .1.3.6.1.4.1.2021.9
              version: 2

    - name: Supprimer la ligne apc-powernet-mib du Makefile pour éviter l'erreur 404
      replace:
        path: "{{ generator_dir }}/generator/Makefile"
        regexp: '^.*apc-powernet-mib.*$'
        replace: ''
      notify: Recharger systemd

    - name: Compiler les MIBs
      command: make mibs
      args:
        chdir: "{{ generator_dir }}/generator"

    - name: Générer le fichier snmp.yml
      command: make generate
      args:
        chdir: "{{ generator_dir }}/generator"

    - name: Copier le fichier snmp.yml généré
      copy:
        src: "{{ generator_dir }}/generator/snmp.yml"
        dest: "{{ snmp_yml_dest }}"
        owner: root
        group: root
        mode: '0644'

    - name: Redémarrer le service snmp_exporter
      systemd:
        name: snmp_exporter
        state: restarted
        daemon_reload: yes
