---
- name: Déployer un endpoint webhook Grafana vers iTop avec gestion firing/resolved
  hosts: itop
  become: yes
  vars:
    itop_webhook_path: "/var/www/html/web/grafana_webhook1.php"
    itop_api_url: "http://10.0.57.36/itop/web/webservices/rest.php?version=1.3"
    itop_login: "rest_user"
    itop_password: "RestUser@123"
    itop_org_id: "4"
    itop_caller_id: "1"

  tasks:
    - name: S'assurer que le répertoire de destination existe
      file:
        path: "/var/www/html/web"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Déployer le script webhook PHP
      copy:
        dest: "{{ itop_webhook_path }}"
        owner: www-data
        group: www-data
        mode: '0644'
        content: |
          <?php
          header('Content-Type: application/json');
          $json = file_get_contents('php://input');
          $data = json_decode($json, true);

          file_put_contents('/tmp/webhook_log.json', print_r($data, true));

          $alert_status = $data['status'] ?? '';
          $alert_name_raw = $data['alerts'][0]['labels']['alertname'] ?? 'Unknown Alert';
          $alert_name = htmlspecialchars($alert_name_raw);
          $description = $data['alerts'][0]['annotations']['description'] ?? 'Alerte sans description';

          $api_url = "{{ itop_api_url }}";
          $auth_user = "{{ itop_login }}";
          $auth_pwd = "{{ itop_password }}";

          function call_itop_api($payload, $api_url, $auth_user, $auth_pwd, $logfile) {
              $options = [
                  'http' => [
                      'header'  => "Content-type: application/json\r\nAuthorization: Basic " . base64_encode("$auth_user:$auth_pwd"),
                      'method'  => 'POST',
                      'content' => json_encode($payload),
                  ],
              ];
              $context  = stream_context_create($options);
              $result = file_get_contents($api_url, false, $context);
              if ($result === false) {
                  file_put_contents($logfile, json_encode(error_get_last()));
              } else {
                  file_put_contents($logfile, $result);
              }
              return $result;
          }

          if ($alert_status == 'firing') {
              $payload = [
                  'operation' => 'core/create',
                  'comment' => 'Création automatique depuis Grafana',
                  'class' => 'UserRequest',
                  'output_fields' => 'id',
                  'fields' => [
                      'org_id' => '{{ itop_org_id }}',
                      'title' => "[Grafana] $alert_name",
                      'description' => $description,
                      'caller_id' => '{{ itop_caller_id }}',
                      'impact' => '2',
                      'urgency' => '2',
                      'priority' => '2',
                      'origin' => 'web',
                  ]
              ];

              call_itop_api($payload, $api_url, $auth_user, $auth_pwd, '/tmp/grafana_ticket_create.json');
          }

          if ($alert_status == 'resolved') {
              $search_title = "[Grafana] $alert_name";

              $search_payload = [
                  'operation' => 'core/get',
                  'class' => 'UserRequest',
                  'key' => "SELECT UserRequest WHERE title = \"$search_title\" AND status != 'closed'",
                  'output_fields' => 'id, status',
              ];

              $result = call_itop_api($search_payload, $api_url, $auth_user, $auth_pwd, '/tmp/grafana_ticket_search.json');
              $response = json_decode($result, true);

              if (!empty($response['objects'])) {
                  foreach ($response['objects'] as $obj) {
                      $ticket_id = $obj['fields']['id'];

                      $update_payload = [
                          'operation' => 'core/update',
                          'class' => 'UserRequest',
                          'key' => $ticket_id,
                          'comment' => 'Clôture automatique depuis Grafana (alerte résolue)',
                          'fields' => [
                              'status' => 'closed',
                          ]
                      ];

                      call_itop_api($update_payload, $api_url, $auth_user, $auth_pwd, '/tmp/grafana_ticket_closed.json');
                  }
              }
          }

          echo json_encode(['status' => 'processed']);
          ?>
