---
- name: Installer et configurer SNMP Exporter en version 0.22.0
  hosts:
    - grafana
    - itop
    - semaphore
  become: yes
  vars:
    snmp_exporter_version: "0.22.0"
    snmp_exporter_url: "https://github.com/prometheus/snmp_exporter/releases/download/v{{ snmp_exporter_version }}/snmp_exporter-{{ snmp_exporter_version }}.linux-amd64.tar.gz"
    snmp_exporter_install_dir: "/usr/local/snmp_exporter"
    snmp_exporter_user: "snmp_exporter"

  tasks:
    - name: Créer l'utilisateur snmp_exporter
      ansible.builtin.user:
        name: "{{ snmp_exporter_user }}"
        shell: /usr/sbin/nologin
        system: yes
        create_home: no

    - name: Créer le dossier d'installation
      ansible.builtin.file:
        path: "{{ snmp_exporter_install_dir }}"
        state: directory
        owner: "{{ snmp_exporter_user }}"
        group: "{{ snmp_exporter_user }}"
        mode: "0755"

    - name: Télécharger SNMP Exporter archive
      ansible.builtin.get_url:
        url: "{{ snmp_exporter_url }}"
        dest: "/tmp/snmp_exporter.tar.gz"
        mode: '0644'

    - name: Extraire SNMP Exporter archive
      ansible.builtin.unarchive:
        src: "/tmp/snmp_exporter.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Copier le binaire snmp_exporter depuis l'hôte distant
      ansible.builtin.copy:
        remote_src: yes
        src: "/tmp/snmp_exporter-{{ snmp_exporter_version }}.linux-amd64/snmp_exporter"
        dest: "{{ snmp_exporter_install_dir }}/snmp_exporter"
        owner: "{{ snmp_exporter_user }}"
        group: "{{ snmp_exporter_user }}"
        mode: '0755'

    - name: Copier la configuration snmp.yml (valide pour if_mib)
      ansible.builtin.copy:
        content: |
          modules:
            if_mib:
              walk:
                - 1.3.6.1.2.1.2
                - 1.3.6.1.2.1.31
              version: 2c
              auth:
                community: public
        dest: "{{ snmp_exporter_install_dir }}/snmp.yml"
        owner: "{{ snmp_exporter_user }}"
        group: "{{ snmp_exporter_user }}"
        mode: '0644'

    - name: Créer le service systemd snmp_exporter
      ansible.builtin.copy:
        dest: /etc/systemd/system/snmp_exporter.service
        content: |
          [Unit]
          Description=Prometheus SNMP Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ snmp_exporter_user }}
          Group={{ snmp_exporter_user }}
          ExecStart={{ snmp_exporter_install_dir }}/snmp_exporter --config.file={{ snmp_exporter_install_dir }}/snmp.yml
          Restart=always

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Recharger systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Activer et démarrer le service snmp_exporter
      ansible.builtin.systemd:
        name: snmp_exporter
        state: started
        enabled: yes
