---
- name: Désinstallation complète SNMP (Exporter, snmpd, Prometheus, générateur)
  hosts:
    - grafana
    - itop
    - semaphore
  become: yes

  vars:
    snmp_exporter_user: "snmp_exporter"
    snmp_exporter_install_dir: "/usr/local/snmp_exporter"
    prometheus_config_path: "/etc/prometheus/prometheus.yml"
    snmp_yml_dest: "/etc/snmp_exporter/snmp.yml"
    generator_dir: "/opt/snmp_exporter_generator"
    generator_packages:
      - git
      - make
      - golang-go
      - libsnmp-dev
      - curl

  tasks:

    # SECTION 1: Désinstallation du snmp_exporter
    - name: "[Exporter] Stopper et désactiver snmp_exporter"
      systemd:
        name: snmp_exporter
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: "[Exporter] Supprimer le fichier systemd de snmp_exporter"
      file:
        path: /etc/systemd/system/snmp_exporter.service
        state: absent

    - name: "[Exporter] Supprimer le répertoire d’installation"
      file:
        path: "{{ snmp_exporter_install_dir }}"
        state: absent

    - name: "[Exporter] Supprimer les fichiers temporaires"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/snmp_exporter.tar.gz
        - /tmp/snmp_exporter-0.28.0.linux-amd64

    - name: "[Exporter] Supprimer l'utilisateur snmp_exporter"
      user:
        name: "{{ snmp_exporter_user }}"
        state: absent
        remove: yes
      ignore_errors: yes

    # SECTION 2: Désinstallation de snmpd (agent)
    - name: "[SNMPD] Attendre la libération du verrou dpkg"
      shell: |
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
          echo "🔒 En attente de la libération du verrou dpkg..."
          sleep 3
        done
      changed_when: false

    - name: "[SNMPD] Stopper et désactiver snmpd"
      systemd:
        name: snmpd
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: "[SNMPD] Supprimer snmpd et ses dépendances"
      apt:
        name: snmpd
        state: absent
        purge: yes
        autoremove: yes
        update_cache: yes

    - name: "[SNMPD] Supprimer les fichiers de configuration snmpd"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/snmp/snmpd.conf
        - /etc/snmp/snmpd.conf.bak
        - /etc/snmp
        - /var/lib/snmp
        - /var/log/snmpd.log

- name: Nettoyage Prometheus sur Grafana
  hosts: grafana
  become: yes
  tasks:
    - name: "[Prometheus] Stopper Prometheus"
      systemd:
        name: prometheus
        state: stopped
      ignore_errors: yes

    - name: "[Prometheus] Restaurer le prometheus.yml d’origine s’il existe"
      copy:
        src: "{{ prometheus_config_path }}.backup"
        dest: "{{ prometheus_config_path }}"
        remote_src: yes
        mode: '0644'
      ignore_errors: yes

    - name: "[Prometheus] Supprimer l’éventuelle sauvegarde restante"
      file:
        path: "{{ prometheus_config_path }}.backup"
        state: absent
      ignore_errors: yes

    - name: "[Prometheus] Redémarrer Prometheus"
      systemd:
        name: prometheus
        state: started
        enabled: yes
      ignore_errors: yes

- name: Nettoyage du générateur SNMP sur Grafana
  hosts: grafana
  become: yes
  tasks:
    - name: "[Générateur] Supprimer le fichier snmp.yml généré"
      file:
        path: "{{ snmp_yml_dest }}"
        state: absent

    - name: "[Générateur] Supprimer le dossier du générateur"
      file:
        path: "{{ generator_dir }}"
        state: absent

    - name: "[Générateur] Supprimer les paquets liés à la génération"
      apt:
        name: "{{ generator_packages }}"
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes

- name: Vérification finale
  hosts: all
  become: yes
  tasks:
    - name: "[Vérif] Afficher confirmation nettoyage complet"
      debug:
        msg: "✅ Tous les composants SNMP ont été supprimés proprement de la machine."
