- name: Initialiser les objets iTop à partir des faits système
  hosts: all
  gather_facts: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"

  tasks:
    - name: Déduire les infos système
      set_fact:
        brand_name: "{{ ansible_product_name.split()[0] | default('HP') }}"
        model_name: "{{ ansible_product_name | default('HP ProLiant') }}"
        os_family: "{{ ansible_os_family | default('Linux') }}"
        os_version: "{{ ansible_distribution_version | default('24.04') }}"

    ##########################
    # Création / récupération Brand
    ##########################
    - name: Créer la marque (Brand)
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/create",
                "class": "Brand",
                "comment": "Créé automatiquement",
                "fields": { "name": brand_name }
              } | to_json
            }}
      register: brand_creation
      failed_when: false

    - name: Récupérer la marque (Brand) si création échouée (existe déjà)
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          version: "1.3"
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Brand",
                "key": "SELECT Brand WHERE name='{{ brand_name }}'",
                "version": "1.3"
              } | to_json
            }}
      when: brand_creation.json.code != 0
      register: brand_query

    - name: Définir brand_id complet (ex: Brand::54)
      set_fact:
        brand_id: >-
          {{
            (brand_creation.json.objects | default({}) | dict2items | first).key
            if brand_creation.json is defined and brand_creation.json.code == 0 else
            (brand_query.json.objects | default({}) | dict2items | first).key
          }}
      when: >
        (brand_creation.json is defined and brand_creation.json.code == 0 and
        brand_creation.json.objects is defined and brand_creation.json.objects | length > 0)
        or
        (brand_query is defined and brand_query.json is defined and brand_query.json.objects is defined and
        brand_query.json.objects | length > 0)

    ##########################
    # Suite du playbook (modèle, osfamily, osversion) avec mêmes protections...
    ##########################

    # Par exemple pour le modèle
    - name: Créer le modèle (Model)
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          json_data: >
            {{
              {
                "operation": "core/create",
                "class": "Model",
                "comment": "Créé automatiquement",
                "fields": {
                  "name": model_name,
                  "brand_id": brand_id
                }
              } | to_json
            }}
      register: model_creation
      failed_when: false

    - name: Récupérer le modèle (Model) si création échouée
      uri:
        url: "{{ itop_url }}"
        method: POST
        user: "{{ itop_user }}"
        password: "{{ itop_password }}"
        force_basic_auth: yes
        body_format: form-urlencoded
        body:
          version: "1.3"
          json_data: >
            {{
              {
                "operation": "core/get",
                "class": "Model",
                "key": "SELECT Model WHERE name='{{ model_name }}'",
                "version": "1.3"
              } | to_json
            }}
      when: model_creation.json.code != 0
      register: model_query

    - name: Définir model_id complet (ex: Model::xx)
      set_fact:
        model_id: >-
          {{
            (model_creation.json.objects | default({}) | dict2items | first).key
            if model_creation.json is defined and model_creation.json.code == 0 else
            (model_query.json.objects | default({}) | dict2items | first).key
          }}
      when: >
        (model_creation.json is defined and model_creation.json.code == 0 and
        model_creation.json.objects is defined and model_creation.json.objects | length > 0)
        or
        (model_query is defined and model_query.json is defined and model_query.json.objects is defined and
        model_query.json.objects | length > 0)

    # Pareil pour OSFamily, OSVersion avec les mêmes gardes.

    ##########################
    # Afficher résultats
    ##########################
    - name: Afficher les résultats de création / récupération
      debug:
        msg:
          - "Marque créée ou existante: {{ brand_creation.json | default(brand_query.json) }}"
          - "Modèle créé ou existant: {{ model_creation.json | default(model_query.json) }}"
