---
- name: Préparer et déployer iTop 3.x sur le serveur
  hosts: itop
  become: yes

  vars:
    itop_version: "3.0.6"
    itop_url: "https://sourceforge.net/projects/itop/files/iTop-{{ itop_version }}/itop-{{ itop_version }}.zip/download"
    itop_zip: "/tmp/itop.zip"
    itop_install_dir: "/var/www/html/web"

  tasks:
    - name: Installer paquets requis (Apache, PHP, unzip, wget)
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - unzip
          - wget
        state: present
        update_cache: yes

    - name: Activer module rewrite d'Apache
      apache2_module:
        name: rewrite
        state: present

    - name: Télécharger iTop archive zip dans /tmp
      get_url:
        url: "{{ itop_url }}"
        dest: "{{ itop_zip }}"
        mode: '0644'

    - name: Supprimer l'ancien dossier iTop s'il existe
      file:
        path: "{{ itop_install_dir }}"
        state: absent

    - name: Créer dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Décompresser iTop dans un dossier temporaire
      unarchive:
        src: "{{ itop_zip }}"
        dest: /tmp/itop
        remote_src: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers extraits dans le dossier d'installation
      command: rsync -a /tmp/itop/ "{{ itop_install_dir }}/"

    - name: Supprimer le dossier temporaire
      file:
        path: /tmp/itop
        state: absent

    - name: Appliquer les permissions sur /var/www/html/web
      file:
        path: "{{ itop_install_dir }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
