---
- name: Installer iTop 3.x (paquets, téléchargement, Apache)
  hosts: itop
  become: yes

  vars:
    itop_url: "https://sourceforge.net/projects/itop/files/latest/download"
    itop_tmp_zip: "/tmp/itop.zip"
    itop_install_dir: "/var/www/html/web"

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-zip
          - unzip
          - wget
        state: present

    - name: Activer module rewrite d'Apache
      apache2_module:
        name: rewrite
        state: present
      notify: Restart Apache

    - name: Télécharger iTop archive zip dans /tmp
      get_url:
        url: "{{ itop_url }}"
        dest: "{{ itop_tmp_zip }}"
        mode: '0644'

    - name: Supprimer ancien dossier iTop s'il existe
      file:
        path: "{{ itop_install_dir }}"
        state: absent

    - name: Créer dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Décompresser iTop dans le dossier web
      unarchive:
        src: "{{ itop_tmp_zip }}"
        dest: "{{ itop_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Appliquer les permissions sur dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
