---
- name: Setup Node Exporters and related services
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.8.2"
    mysql_exporter_version: "0.17.2"
   
    
    node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mysqld_exporter_url: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysql_exporter_version }}/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64.tar.gz"
    
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    # Node Exporter Installation
    - name: Install Node Exporter
      block:
        - name: Download Node Exporter
          get_url:
            url: "{{ node_exporter_url }}"
            dest: "/tmp/node_exporter.tar.gz"
        
        - name: Extract Node Exporter
          unarchive:
            src: "/tmp/node_exporter.tar.gz"
            dest: "/tmp"
            remote_src: yes

        - name: Move Node Exporter to /usr/local/bin
          command:
            cmd: mv /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter /usr/local/bin/

        - name: Make Node Exporter executable
          file:
            path: /usr/local/bin/node_exporter
            mode: '0755'

        - name: Create node_exporter user
          user:
            name: node_exporter
            shell: /bin/false
            system: yes

        - name: Create Node Exporter systemd service
          copy:
            content: |
              [Unit]
              Description=Node Exporter
              After=network.target

              [Service]
              User=node_exporter
              Group=node_exporter
              ExecStart=/usr/local/bin/node_exporter

              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/node_exporter.service
            mode: '0644'

        - name: Reload systemd
          systemd:
            daemon_reload: yes

        - name: Start Node Exporter service
          systemd:
            name: node_exporter
            state: started
            enabled: yes
    # MySQL Exporter Installation
    - name: Install MySQL Exporter
      block:
        - name: Download MySQL Exporter
          get_url:
            url: "{{ mysqld_exporter_url }}"
            dest: "/tmp/mysqld_exporter.tar.gz"

        - name: Extract MySQL Exporter
          unarchive:
            src: "/tmp/mysqld_exporter.tar.gz"
            dest: "/tmp"
            remote_src: yes

        - name: Move MySQL Exporter to /usr/local/bin
          command:
            cmd: mv /tmp/mysqld_exporter-{{ mysql_exporter_version }}.linux-amd64/mysqld_exporter /usr/local/bin/

        - name: Make MySQL Exporter executable
          file:
            path: /usr/local/bin/mysqld_exporter
            mode: '0755'

        - name: Create mysqld_exporter user
          user:
            name: mysqld_exporter
            shell: /bin/false
            system: yes

        - name: Create MySQL Exporter systemd service
          copy:
            content: |
              [Unit]
              Description=MySQL Exporter
              Documentation=https://github.com/prometheus/mysqld_exporter

              [Service]
              ExecStart=/usr/local/bin/mysqld_exporter --web.listen-address=0.0.0.0:9104
              User=mysqld_exporter
              Group=mysqld_exporter
              Restart=always

              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/mysqld_exporter.service
            mode: '0644'

        - name: Reload systemd
          systemd:
            daemon_reload: yes

        - name: Start MySQL Exporter service
          systemd:
            name: mysqld_exporter
            state: started
            enabled: yes

    
