---
- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: all
  become: yes

  vars:
    itop_url: "https://github.com/Combodo/iTop/releases/download/3.2.1-1/iTop-3.2.1-1-16749.zip"
    itop_zip_path: "/tmp/iTop-3.2.1.zip"
    itop_web_dir: "/var/www/html"
    itop_extract_dir: "/tmp/itop_extract"

  tasks:
    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-mbstring
          - php-xml
          - php-zip
          - unzip
          - wget
          - python3-pip
        state: present
        update_cache: yes

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Démarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Télécharger iTop
      get_url:
        url: "{{ itop_url }}"
        dest: "{{ itop_zip_path }}"
        mode: '0644'
        force: yes

    - name: Créer le dossier temporaire pour l'extraction
      file:
        path: "{{ itop_extract_dir }}"
        state: directory
        mode: '0755'

    - name: Décompresser iTop dans le dossier temporaire
      unarchive:
        src: "{{ itop_zip_path }}"
        dest: "{{ itop_extract_dir }}"
        remote_src: yes

    - name: Vider le répertoire web existant
      file:
        path: "{{ itop_web_dir }}"
        state: absent

    - name: Recréer le répertoire web
      file:
        path: "{{ itop_web_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers extraits vers le répertoire web
      command: rsync -a {{ itop_extract_dir }}/ {{ itop_web_dir }}/

    - name: Supprimer le dossier temporaire d'extraction
      file:
        path: "{{ itop_extract_dir }}"
        state: absent

    - name: Appliquer les bonnes permissions
      file:
        path: "{{ itop_web_dir }}"
        owner: www-data
        group: www-data
        recurse: yes
