---
- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: itop
  become: yes
  vars:
    itop_version: "3.2.1-1"
    itop_url: "https://github.com/Combodo/iTop/releases/download/3.2.1-1/iTop-3.2.1-1-16749.zip"
    itop_install_dir: "/var/www/html/itop"

  tasks:
    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-curl
          - php-mbstring
          - php-gd
          - unzip
          - wget
          - mysql-client
          - mysql-server
        state: present
        update_cache: yes

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Démarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Télécharger iTop
      get_url:
        url: "{{ itop_url }}"
        dest: "/tmp/iTop-{{ itop_version }}.zip"
        mode: '0644'

    - name: Décompresser iTop dans le répertoire web
      unarchive:
        src: "/tmp/iTop-{{ itop_version }}.zip"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Renommer le dossier en itop
      command: mv "/var/www/html/web" "{{ itop_install_dir }}"
      args:
        creates: "{{ itop_install_dir }}"

    - name: Appliquer les bonnes permissions
      file:
        path: "{{ itop_install_dir }}"
        owner: www-data
        group: www-data
        recurse: yes
