---
- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: itop
  become: yes

  vars:
    itop_url: "https://github.com/Combodo/iTop/releases/download/3.2.1-1/iTop-3.2.1-1-16749.zip"
    itop_zip_path: "/tmp/iTop-3.2.1.zip"
    itop_web_dir: "/var/www/html"
    itop_extract_dir: "/tmp/itop_extract"

  tasks:

    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-mbstring
          - php-xml
          - php-soap
          - php-zip
          - unzip
          - wget
          - python3-pip
        state: present

    - name: Activer le module rewrite d'Apache
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Autoriser l'utilisation des .htaccess dans Apache
      lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^<Directory /var/www/>'
        insertafter: '^<Directory /var/www/>'
        line: '    AllowOverride All'
        state: present

    - name: Télécharger iTop
      get_url:
        url: "{{ itop_url }}"
        dest: "{{ itop_zip_path }}"
        mode: '0644'
        force: yes

    - name: Créer le dossier temporaire pour l'extraction
      file:
        path: "{{ itop_extract_dir }}"
        state: directory
        mode: '0755'

    - name: Décompresser iTop dans le dossier temporaire
      unarchive:
        src: "{{ itop_zip_path }}"
        dest: "{{ itop_extract_dir }}"
        remote_src: yes

    - name: Trouver le dossier iTop extrait
      find:
        paths: "{{ itop_extract_dir }}"
        file_type: directory
        patterns: "iTop-*"
        recurse: false
      register: itop_folder

    - name: Échouer si le dossier iTop n'a pas été trouvé
      fail:
        msg: "Le dossier extrait iTop n'a pas été trouvé. Vérifie le fichier ZIP."
      when: itop_folder.files | length == 0

    - name: Définir le chemin complet du dossier iTop
      set_fact:
        itop_extracted_path: "{{ itop_folder.files[0].path }}"

    - name: Vider le répertoire web existant
      file:
        path: "{{ itop_web_dir }}"
        state: absent

    - name: Recréer le répertoire web
      file:
        path: "{{ itop_web_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers extraits vers le répertoire web
      command: rsync -a {{ itop_extracted_path }}/ {{ itop_web_dir }}/

    - name: Créer un fichier .htaccess pour rediriger vers /web
      copy:
        dest: "{{ itop_web_dir }}/.htaccess"
        content: |
          RewriteEngine On
          RewriteCond %{REQUEST_URI} !^/web/
          RewriteRule ^(.*)$ /web/$1 [L]

    - name: Appliquer les bonnes permissions sur le répertoire web
      file:
        path: "{{ itop_web_dir }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Supprimer le dossier temporaire d'extraction
      file:
        path: "{{ itop_extract_dir }}"
        state: absent

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
