---
- name: Préparer et déployer iTop 3.x sur le serveur
  hosts: itop
  become: yes

  vars:
    itop_download_url: "https://sourceforge.net/projects/itop/files/latest/download"
    itop_install_dir: "/var/www/html/web"

  tasks:
    - name: Installer les paquets requis (Apache, PHP, unzip, wget)
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-zip
          - php-gd
          - php-intl
          - php-bcmath
          - php-cli
          - unzip
          - wget
        state: present
        update_cache: yes

    - name: Activer module rewrite d'Apache
      apache2_module:
        name: rewrite
        state: present
      notify: Restart Apache

    - name: Télécharger iTop archive zip dans /tmp
      get_url:
        url: "{{ itop_download_url }}"
        dest: /tmp/itop.zip
        mode: '0644'

    - name: Supprimer l'ancien dossier iTop si existe
      file:
        path: "{{ itop_install_dir }}"
        state: absent

    - name: Créer dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Décompresser iTop dans le dossier web
      unarchive:
        src: /tmp/itop.zip
        dest: "{{ itop_install_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
        owner: www-data
        group: www-data

    - name: Appliquer permissions sur dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
