- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: itop
  become: yes

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-cli
          - unzip
          - wget
          - mysql-server
        state: present

    - name: Activer le module rewrite d'Apache
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Ajouter un bloc Directory complet pour /var/www/html dans apache2.conf
      blockinfile:
        path: /etc/apache2/apache2.conf
        block: |
          <Directory /var/www/html/>
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

    - name: Télécharger iTop
      get_url:
        url: https://sourceforge.net/projects/itop/files/latest/download
        dest: /tmp/itop.zip

    - name: Créer le dossier temporaire pour extraction
      file:
        path: /tmp/itop
        state: directory

    - name: Décompresser iTop
      unarchive:
        src: /tmp/itop.zip
        dest: /tmp/itop
        remote_src: yes

    - name: Supprimer le contenu du répertoire web existant
      file:
        path: /var/www/html
        state: absent

    - name: Recréer le répertoire web
      file:
        path: /var/www/html
        state: directory

    - name: Copier seulement le contenu utile vers /var/www/html
      shell: |
        shopt -s dotglob
        cp -r /tmp/itop/* /var/www/html/
      args:
        executable: /bin/bash

    - name: Créer un .htaccess pour redirection vers /web
      copy:
        dest: /var/www/html/.htaccess
        content: |
          DirectoryIndex web/index.php

    - name: Appliquer les permissions
      file:
        path: /var/www/html
        recurse: yes
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Supprimer le dossier temporaire
      file:
        path: /tmp/itop
        state: absent

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
