---
- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: itop
  become: yes
  vars:
    itop_version: "3.1.1"
    itop_url: "https://sourceforge.net/projects/itop/files/iTop%20Stable%20Releases/3.1.1/iTop-3.1.1.zip/download"
    itop_install_dir: "/var/www/html/itop"
    db_name: "itop_db"
    db_user: "itop_user"
    db_password: "itop_password"
    mysql_root_password: "rootpass"

  tasks:
    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-xml
          - php-curl
          - php-mbstring
          - php-gd
          - unzip
          - wget
          - mysql-client
          - mysql-server
        state: present
        update_cache: yes

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Démarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Télécharger iTop
      get_url:
        url: "{{ itop_url }}"
        dest: "/tmp/iTop-{{ itop_version }}.zip"
        mode: '0644'

    - name: Décompresser iTop dans le répertoire web
      unarchive:
        src: "/tmp/iTop-{{ itop_version }}.zip"
        dest: "/var/www/html/"
        remote_src: yes

    - name: Renommer le dossier en itop
      command: mv "/var/www/html/iTop-{{ itop_version }}" "{{ itop_install_dir }}"
      args:
        removes: "/var/www/html/iTop-{{ itop_version }}"
        creates: "{{ itop_install_dir }}"

    - name: Appliquer les bonnes permissions sur le dossier iTop
      file:
        path: "{{ itop_install_dir }}"
        owner: www-data
        group: www-data
        recurse: yes
