---
- name: Installation de NGINX
  hosts: itop
  become: yes
  tasks:
    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Démarrer et activer nginx
      service:
        name: nginx
        state: started
        enabled: yes
