---
- name: Installer iTop (Apache, PHP, MySQL, fichiers)
  hosts: all
  become: yes
  vars:
    itop_url: "https://github.com/Combodo/iTop/releases/download/3.2.1-1/iTop-3.2.1-1-16749.zip"
    itop_zip_path: "/tmp/iTop-3.2.1.zip"
    itop_web_dir: "/var/www/html"

  tasks:
    - name: Installer les paquets requis
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-mbstring
          - php-xml
          - php-zip
          - unzip
          - wget
          - python3-pip
        state: present
        update_cache: yes

    - name: Démarrer Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Démarrer MySQL
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Télécharger iTop
      get_url:
        url: "{{ itop_url }}"
        dest: "{{ itop_zip_path }}"
        mode: '0644'
        force: yes

    - name: Décompresser iTop dans le répertoire web
      unarchive:
        src: "{{ itop_zip_path }}"
        dest: "{{ itop_web_dir }}"
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Appliquer les bonnes permissions sur le répertoire web
      file:
        path: "{{ itop_web_dir }}"
        owner: www-data
        group: www-data
        recurse: yes
