---
- name: Installer et démarrer Nginx sur les serveurs
  hosts: all
  become: yes

  tasks:
    - name: Mettre à jour le cache des paquets apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer Nginx
      apt:
        name: nginx
        state: present

    - name: Modifier le port d'écoute de Nginx si hôte = 10.0.57.36
      when: ansible_host == "10.0.57.36"
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen 80 default_server;'
        replace: 'listen 8080 default_server;'

    - name: Modifier aussi la ligne IPv6 si hôte = 10.0.57.36
      when: ansible_host == "10.0.57.36"
      replace:
        path: /etc/nginx/sites-available/default
        regexp: 'listen \[::\]:80 default_server;'
        replace: 'listen [::]:8080 default_server;'

    - name: Redémarrer Nginx pour prendre en compte les changements
      systemd:
        name: nginx
        state: restarted
        enabled: yes

    - name: Vérifier que Nginx écoute sur le bon port
      wait_for:
        port: "{{ '8080' if ansible_host == '10.0.57.36' else '80' }}"
        timeout: 10
