---
- name: Enregistrer automatiquement les serveurs dans iTop
  hosts: all
  gather_facts: true
  become: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"

  tasks:
    - import_tasks: playbooks/tasks/osfamily.yml
    - import_tasks: playbooks/tasks/osversion.yml
    - import_tasks: playbooks/tasks/location.yml

    - name: Créer le serveur dans iTop
      include_role:
        name: combodo.itop.core.write
      vars:
        itop_class: "Server"
        itop_fields:
          name: "{{ inventory_hostname }}"
          organization_name: "API Users"
          status: "production"
          osfamily_name: "{{ os_family_name }}"
          osversion_name: "{{ os_version_name }}"
          location_name: "{{ location_name }}"
