---
- name: Enregistrer automatiquement les serveurs dans iTop
  hosts: all
  gather_facts: true
  become: yes
  vars:
    itop_url: "http://10.0.57.36/web/webservices/rest.php"
    itop_user: "rest_user"
    itop_password: "RestUser@123"

  tasks:
    - import_tasks: playbooks/tasks/osfamily.yml
    - import_tasks: playbooks/tasks/osversion.yml
    - import_tasks: playbooks/tasks/location.yml
    - import_tasks: playbooks/tasks/get_ids.yml
    - name: Créer le serveur dans iTop
      include_role:
        name: combodo.itop.core.write
      vars:
        itop_version: "1.3"  # <- C'est cette ligne qui manquait
        itop_class: "Server"
        itop_fields:
          name: "{{ inventory_hostname }}"
          org_id: "4"
          status: "production"
          osfamily_id: "{{ osfamily_id }}"
          osversion_id: "{{ osversion_id }}"
          location_id: "{{ location_id }}"
          cpu: "{{ ansible_processor[1] | default('N/A') }}"
          ram: "{{ ansible_memtotal_mb | default('0') }} MB"
          description: "Créé automatiquement par Ansible"
