---
- name: Redémarrer un service système
  hosts: all
  become: yes
  vars:
    service_name: mysql  # Valeur par défaut, sera remplacée par Semaphore

  tasks:
    - name: Redémarrer le service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: restarted
