---
- name: Mise à jour des paquets sur le serveur GLPI
  hosts: glpi
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour les paquets installés
      apt:
        upgrade: dist
