---
- name: Mise à jour des paquets
  hosts: ubuntu
  become: yes
  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Mettre à jour tous les paquets installés
      apt:
        upgrade: dist
