---
- name: Créer un contact point Webhook dans Grafana avec auth basique
  hosts: grafana
  become: yes
  vars:
    grafana_api_url: "http://10.0.57.35:3000/api/contact-points"
    grafana_user: "admin"           # Remplace par ton login Grafana admin
    grafana_password: "12345"       # Remplace par ton mot de passe Grafana admin
    itop_webhook_url: "http://10.0.57.36/itop/web/webservices/rest.php?version=1.3"

  tasks:
    - name: Créer le contact point webhook iTop
      uri:
        url: "{{ grafana_api_url }}"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "iTop Webhook"
          type: webhook
          settings:
            url: "{{ itop_webhook_url }}"
            httpMethod: POST
            autoResolve: true
            maxRetries: 3
          disableResolveMessage: false
          enable: true
        status_code: [200, 202, 409]
      register: grafana_response

    - name: Afficher la réponse de Grafana
      debug:
        var: grafana_response
