---
- name: Configurer webhook Legacy Alerting dans Grafana
  hosts: grafana
  become: yes
  vars:
    grafana_api_url_base: "http://10.0.57.35:3000/api"
    grafana_user: "admin"
    grafana_password: "12345"
    itop_webhook_url: "http://10.0.57.36/itop/web/webservices/rest.php?version=1.3"
    datasource_uid: "deq4dop13tgjkd"

  tasks:
    - name: Créer le receiver webhook iTop (Legacy)
      uri:
        url: "{{ grafana_api_url_base }}/alert-notifications"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          name: "iTop Webhook"
          type: "webhook"
          settings:
            url: "{{ itop_webhook_url }}"
            httpMethod: "POST"
            autoResolve: true
            sendResolved: true
          frequency: "1m"
          disableResolveMessage: false
          sendReminder: false
        status_code: [200, 202, 409]
      register: receiver_response

    - name: Afficher la réponse création receiver
      debug:
        var: receiver_response

    - name: Créer une règle d'alerte "MySQL DOWN" liée au webhook
      uri:
        url: "{{ grafana_api_url_base }}/alerts"
        method: POST
        user: "{{ grafana_user }}"
        password: "{{ grafana_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          dashboardUid: null
          panelId: 1
          name: "MySQL DOWN"
          folderUid: "general"
          condition: "A"
          data:
            - refId: "A"
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: "{{ datasource_uid }}"
              model:
                expr: "mysql_up == 0"
                format: "time_series"
                interval: ""
                intervalFactor: 2
                legendFormat: ""
                refId: "A"
          noDataState: "NoData"
          execErrState: "Error"
          for: "5m"
          annotations: {}
          labels:
            severity: "critical"
          alerts:
            - receiver: "iTop Webhook"
          frequency: "1m"
        status_code: [200, 202, 409]
      register: alert_response

    - name: Afficher la réponse création règle d'alerte
      debug:
        var: alert_response
