---
- name: Provisionner un contact point webhook dans Grafana (Unified Alerting)
  hosts: grafana
  become: yes
  vars:
    provisioning_dir: "/etc/grafana/provisioning/alerting"
    contact_point_file: "itop-webhook.yaml"
    webhook_url: "http://10.0.57.36/web/grafana_webhook1.php"

  tasks:
    - name: Créer le fichier de contact point YAML
      copy:
        dest: "{{ provisioning_dir }}/{{ contact_point_file }}"
        content: |
          contactPoints:
            - orgId: 1
              name: "iTop Webhook"
              receivers:
                - uid: "itop-webhook"
                  type: "webhook"
                  settings:
                    url: "{{ webhook_url }}"
                    httpMethod: "POST"
                    autoResolve: true
                    sendResolved: true

    - name: Redémarrer Grafana pour appliquer le contact point
      systemd:
        name: grafana-server
        state: restarted
