---
- name: Récupérer l'ID de OS Family
  uri:
    url: "{{ itop_url }}"
    method: POST
    user: "{{ itop_user }}"
    password: "{{ itop_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      operation: core/get
      class: OSFamily
      key: "name = '{{ os_family_name }}'"
    return_content: yes
  register: osfamily_result

- name: Récupérer l'ID de OS Version
  uri:
    url: "{{ itop_url }}"
    method: POST
    user: "{{ itop_user }}"
    password: "{{ itop_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      operation: core/get
      class: OSVersion
      key: "name = '{{ os_version_name }}'"
    return_content: yes
  register: osversion_result

- name: Récupérer l'ID de la Localisation
  uri:
    url: "{{ itop_url }}"
    method: POST
    user: "{{ itop_user }}"
    password: "{{ itop_password }}"
    force_basic_auth: yes
    body_format: json
    body:
      operation: core/get
      class: Location
      key: "name = '{{ location_name }}'"
    return_content: yes
  register: location_result

- name: Enregistrer les facts avec les IDs extraits
  set_fact:
    osfamily_id: "{{ (osfamily_result.json.objects | default({})) | dict2items | first.value.key | default('') }}"
    osversion_id: "{{ (osversion_result.json.objects | default({})) | dict2items | first.value.key | default('') }}"
    location_id: "{{ (location_result.json.objects | default({})) | dict2items | first.value.key | default('') }}"
