---
- name: Déduire la localisation selon l'adresse IP
  set_fact:
    location_name: >
      {% if ansible_default_ipv4.address is search("10.0.57") %}
        Bamako-Daoudabougou
      {% elif ansible_default_ipv4.address is search("10.1.") %}
        Bamako-Hamdallaye
      {% else %}
        Inconnue
      {% endif %}
