---
- name: Déduire la famille de l'OS
  set_fact:
    os_family_name: >
      {% if ansible_facts['os_family'] == "Debian" %}
        Linux
      {% elif ansible_facts['os_family'] == "RedHat" %}
        Linux
      {% elif ansible_facts['os_family'] == "Windows" %}
        Windows
      {% else %}
        Autre
      {% endif %}
