---
- name: Créer un serveur dans iTop
  uri:
    url: "{{ itop_url }}"
    method: POST
    user: "{{ itop_user }}"
    password: "{{ itop_password }}"
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      version: "1.3"  # Obligatoire pour l'API iTop
      json_data: >-
        {{
          {
            "operation": "core/create",
            "class": "Server",
            "comment": "Création automatique via Ansible",
            "fields": {
              "name": ansible_hostname,
              "org_id": default_org_id,
              "location_id": default_location_id,
              "cpu": ansible_processor[1] | default('Non spécifié'),
              "ram": (ansible_memtotal_mb | default(0)) ~ " MB",
              "description": "Serveur ajouté automatiquement par Ansible"
            }
          } | to_json
        }}
    return_content: yes
  register: itop_response

- name: Afficher la réponse d’iTop
  debug:
    var: itop_response.content
