---
- name: Créer un objet dans iTop via l’API REST
  uri:
    url: "{{ itop_url }}"
    method: POST
    user: "{{ itop_user }}"
    password: "{{ itop_password }}"
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      version: "{{ itop_version }}"
      json_data: >
        {
          "operation": "core/create",
          "class": "{{ itop_class }}",
          "comment": "Création depuis Ansible",
          "fields": {{ itop_fields | to_json }}
        }
    return_content: yes
  register: itop_result

- name: Afficher la réponse de l’API iTop
  debug:
    var: itop_result.json
